export const PRECISION = 4;
export const DELAY = 400;
export const CURRENCY_INFO =  [
        {name: 'EUR', description: 'Euro' },
        {name: 'JPY', description: 'Japanese yen' },
        {name: 'BGN', description: 'Bulgarian lev' },
        {name: 'CZK', description: 'Czech koruna' },
        {name: 'DKK', description: 'Danish krone' },
        {name: 'GBP', description: 'Pound sterling' },
        {name: 'HUF', description: 'Hungarian forint' },
        {name: 'PLN', description: 'Polish zloty' },
        {name: 'RON', description: 'Romanian leu' },
        {name: 'SEK', description: 'Swedish krona' },
        {name: 'CHF', description: 'Swiss franc' },
        {name: 'ISK', description: 'Icelandic krona' },
        {name: 'NOK', description: 'Norwegian krone' },
        {name: 'USD', description: 'US dollar' },
        {name: 'HOK', description: 'Croatian kuna' },
        {name: 'RUB', description: 'Russian rouble' },
        {name: 'TRY', description: 'Turkish lira' },
        {name: 'AUD', description: 'Australian dollar' },
        {name: 'BRL', description: 'Brazilian real' },
        {name: 'CAD', description: 'Canadian dollar' },
        {name: 'CNY', description: 'Chinese yuan renminbi' },
        {name: 'HKD', description: 'Hong Kong dollar' },
        {name: 'IDR', description: 'Indonesian rupiah' },
        {name: 'ILS', description: 'Israeli shekel' },
        {name: 'INR', description: 'Indian rupee' },
        {name: 'KRW', description: 'South Korean won' },
        {name: 'MXN', description: 'Mexican peso' },
        {name: 'MYR', description: 'Malaysian ringgit' },
        {name: 'NZD', description: 'New Zealand dollar' },
        {name: 'PHP', description: 'Philippine peso' },
        {name: 'SGD', description: 'Singapore dollar' },
        {name: 'THB', description: 'Thai baht' },
        {name: 'ZAR', description: 'South African rand' }
    ];